spring: 
  datasource: 
    url: jdbc:h2:mem:ejmplo1
    username: sa 
    password: 
    driverClassName: org.h2.Driver 
  jpa: 
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect 
    #propiedades hibernate 
    spring.jpa.hibernate.ddl-auto: update  
  h2: 
    console.path: /h2-console 
    console.settings.trace: false 
    spring.h2.console.settings.web-allow-others: false 